# -*- coding: utf-8 -*-
"""10_2111140060_山田翔也.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nA37x-SfoqEMiI4OPrwty5gl1xLEkyt2
"""

tape = ["B", "b", "x", ">", "e", "B", "B", "B", "B", "B", "B"]
pt=2
state="q0"
MF=[["q0","b","q0","b","R"],["q0","x","q1","_","R"]]
print("テープ:書き換え前")
for s in tape:
    print(s,end="")
print()
for mf in MF:
    if((mf[0]==state)&(mf[1]==tape[pt])):
        tape[pt]=mf[3]
        state=mf[2]
        if(mf[4]=="R"):
            pt+=1
        else:
            pt-=1
        break
print("テープ:書き換え後")
for s in tape:
    print(s,end="")
print()

def fact_for(n):
  r = 1
  for i in range(n):
    r *= i+1
  return r

print(fact_for(5))

def fact_rec(n):
  if (n > 0):
    return n * fact_rec(n-1)
  else:
    return 1

print(fact_rec(5))